# Generated by Django 5.1.1 on 2024-10-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
