# Generated by Django 5.1.1 on 2024-10-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_updated_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_status',
            field=models.CharField(choices=[('NEW', 'New'), ('VERIFIED_CODE', 'Verified_code'), ('DONE', 'Done'), ('PHONE_STEP', 'Photo_step')], default='NEW', max_length=13),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_type',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('PHONE', 'Phone')], default='EMAIL', max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OPTIONAL', 'Optional')], default='OPTIONAL', max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('ORDINARY_USER', 'Ordinary_user')], default='ORDINARY_USER', max_length=13),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='verify_type',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('PHONE', 'Phone')], max_length=5),
        ),
    ]
