# Generated by Django 5.1.1 on 2024-10-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userconfirmation_verify_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_status',
            field=models.CharField(choices=[('NEW', 'New'), ('VERIFY_CODE', 'Verify code'), ('DONE', 'Done'), ('PHOTO_DONE', 'Photo done')], default='NEW', max_length=11),
        ),
    ]
