# Generated by Django 5.1.1 on 2024-10-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_auth_status_alter_user_auth_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_status',
            field=models.CharField(choices=[('NEW', 'New'), ('VERIFIED_CODE', 'Verified_code'), ('DONE', 'Done'), ('PHONE_STEP', 'Photo_step')], max_length=13),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_type',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('PHONE', 'Phone')], max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OPTIONAL', 'Optional')], max_length=8),
        ),
    ]
